### ISSUE TITLE
Crash "`concat': no implicit conversion of Set into Array (TypeError)"

### ISSUE THREAD

**Issue by tkrotoff** [spk/validate-website#13]
Full stack trace:
```
bundle exec rake validate-website
validating [...]

./vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:130:in `concat': no implicit conversion of Set into Array (TypeError)
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:130:in `block in check_static_not_found'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:121:in `each'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:121:in `check_static_not_found'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:68:in `block in crawl_static'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:61:in `each'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/core.rb:61:in `crawl_static'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/lib/validate_website/runner.rb:23:in `run_static'
	from /vendor/bundle/ruby/2.0.0/gems/validate-website-1.0.1/bin/validate-website-static:5:in `<top (required)>'
	from /vendor/bundle/ruby/2.0.0/bin/validate-website-static:23:in `load'
	from /vendor/bundle/ruby/2.0.0/bin/validate-website-static:23:in `<main>'
```

Here my Rakefile (same as the one from your README) for my Jekyll website:

```Ruby
desc "Validate _site with validate-website"
task 'validate-website' do
  Dir.chdir('./_site') do
    system("bundle exec validate-website-static --site '[...]' --verbose --markup --not-found") do |ok, res|
      unless ok
        puts "validate error (status = #{res.exitstatus})"
      end
    end
  end
end
```

I order to debug I've added
`p "extract_urls_from_css(css_page)=#{extract_urls_from_css(css_page).to_a}"`
to [core.rb](https://github.com/spk/validate-website/blob/v1.0.1/lib/validate_website/core.rb#L130)
It displays: `"extract_urls_from_css(css_page)=[nil]"`.
So function extract_urls_from_css() has a problem.

Looking at the [code](https://github.com/spk/validate-website/blob/v1.0.1/lib/validate_website/core.rb#L148), it is missing a declaration: `result = []` and the last statement `result`:
```Ruby
def extract_urls_from_css(page)
  p "extract_urls_from_css"
  result = [] # <===== Declaration
  page.body.scan(/url\((['".\/\w-]+)\)/).reduce(Set[]) do |result, url|
    url = url.first.gsub("'", "").gsub('"', '')
    abs = page.to_absolute(URI.parse(url))
    p "url=#{url}"
    p "URI.parse(url)=#{URI.parse(url)}"
    p "abs=#{abs}"
    result << abs
  end
  p "result=#{result}"
  result # <===== Last statement
end
```

It then works (no more crash) with the following debug infos thx to the puts():
```
bundle exec rake validate-website
validating [...]

."extract_urls_from_css"
"url=/assets/8-rue-Desnouettes/Cabinet3-header-bg.jpg"
"URI.parse(url)=/assets/8-rue-Desnouettes/Cabinet3-header-bg.jpg"
"abs="
"result=[]"
"extract_urls_from_css(css_page)=[]"
"extract_urls_from_css"
"url=/assets/8-rue-Desnouettes/Cabinet3-header-bg.jpg"
"URI.parse(url)=/assets/8-rue-Desnouettes/Cabinet3-header-bg.jpg"
"abs="
"result=[]"
```

(I find it strange that my website url (http://....) specified with `--site` is not prepend to /assets/8-rue-Desnouettes/Cabinet3-header-bg.jpg - I have no idea if there is a problem here and how it should work, it is just a feeling).

**Comment by spk** [comment]
Thanks for your feedback :exclamation:
